# Update the NODE_VERSION arg in docker-compose.yml to pick a Node version: 10, 12, 14
ARG NODE_VERSION=20
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:${NODE_VERSION}

# Hugo dev server port
EXPOSE 1313
